version: "3.8"
services:
  # Spring Boot (Backend)
  spring:
    image: kimkyeongeun/springboot:latest
    container_name: spring
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - LOGSTASH_HOST=docker-elk_logstash_1
      - LOGSTASH_PORT=5044
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - default
      - docker-elk_elk

  fastapi:
    image: kimkyeongeun/fastapi:latest
    container_name: fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - LOGSTASH_HOST=docker-elk_logstash_1
      - LOGSTASH_PORT=5044
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - default
      - docker-elk_elk

  # Emotion API Server 수정
  emotion-api:
    image: kimkyeongeun/emotion-api:latest
    container_name: emotion-api
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - LOGSTASH_HOST=docker-elk_logstash_1
      - LOGSTASH_PORT=5044
    networks:
      - default
      - docker-elk_elk

  # MySQL (RDB)
  mysql:
    image: mysql:8
    container_name: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis (Cache)
  redis:
    image: redis:7
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      retries: 5

  # Nginx (Web Server/Proxy)
  nginx:
    image: nginx:latest  # 공식 Nginx 이미지로 변경
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - spring
      - fastapi

networks:
  default:
    driver: bridge

volumes:
  mysql-data:
  redis-data: