spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/buds?useSSL=false # &serverTimezone=UTC
    username: localhost
    password: localhost

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
      # location: C:/board/upload/

# JWT
jwt:
  secret: yourSecretKeyyourSecretKeyyourSecretKeyyourSecretKey
  expiration: 86400000
  access-expiration-time: 3600000  # 1 hour
  refresh-expiration-time: 86400000  # 1 day