global:
  scrape_interval: 30s
  evaluation_interval: 30s

# 알림 설정 유지
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metric_relabel_configs:
      # 필요한 메트릭만 수집하도록 설정
      - source_labels: [__name__]
        regex: 'node_(cpu|memory|disk|filesystem|network|load|boot_time).*'
        action: keep

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metric_relabel_configs:
      # 컨테이너 메트릭 필터링
      - source_labels: [__name__]
        regex: 'container_(cpu|memory|network|fs).*'
        action: keep

  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring:8080']

  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['fastapi:8000']